"""Environment file management.

Handles .env file creation, secure storage, and symlinking into releases.
"""

from pathlib import Path
from typing import Optional

from rich.console import Console
from rich.prompt import Confirm, Prompt
from rich.table import Table

from deploycraft.config import get_envs_dir
from deploycraft.utils import (
    generate_secret_key,
    success,
    warning,
    write_file_secure,
)

console = Console()

# Common env vars that DeployCraft can auto-populate
AUTO_POPULATE_VARS = {
    "DATABASE_URL": "Auto-generated from PostgreSQL setup",
    "DB_NAME": "Auto-generated from project name",
    "DB_USER": "Auto-generated from project name",
    "DB_PASSWORD": "Auto-generated secure password",
    "DB_HOST": "localhost",
    "DB_PORT": "5432",
    "REDIS_URL": "redis://localhost:6379/0",
    "SECRET_KEY": "Auto-generated secure key",
    "DEBUG": "False",
    "ALLOWED_HOSTS": "Domain name from setup",
}

# Vars commonly found in Django projects
DJANGO_COMMON_VARS = [
    "SECRET_KEY",
    "DEBUG",
    "ALLOWED_HOSTS",
    "DATABASE_URL",
    "REDIS_URL",
    "CELERY_BROKER_URL",
    "EMAIL_HOST",
    "EMAIL_PORT",
    "EMAIL_HOST_USER",
    "EMAIL_HOST_PASSWORD",
    "AWS_ACCESS_KEY_ID",
    "AWS_SECRET_ACCESS_KEY",
    "AWS_STORAGE_BUCKET_NAME",
]

# Vars commonly found in Next.js/Node projects
NODE_COMMON_VARS = [
    "NODE_ENV",
    "PORT",
    "DATABASE_URL",
    "NEXT_PUBLIC_API_URL",
    "JWT_SECRET",
    "REDIS_URL",
]


def get_env_file_path(project_name: str) -> Path:
    """Get the secure path for a project's .env file.

    Args:
        project_name: Name of the project.

    Returns:
        Path to the .env file in the secure envs directory.
    """
    env_dir = get_envs_dir() / project_name
    env_dir.mkdir(parents=True, exist_ok=True)
    return env_dir / ".env"


def create_env_file(
    project_name: str,
    env_vars: dict[str, str],
) -> Path:
    """Create a .env file with the given variables.

    Args:
        project_name: Name of the project.
        env_vars: Dictionary of environment variable key-value pairs.

    Returns:
        Path to the created .env file.
    """
    env_path = get_env_file_path(project_name)

    # Build .env content
    lines = [f"# DeployCraft environment file for: {project_name}"]
    lines.append("# Generated by DeployCraft")
    lines.append("")

    for key, value in env_vars.items():
        # Quote values that contain spaces or special chars
        if " " in value or "'" in value or '"' in value or "#" in value:
            lines.append(f'{key}="{value}"')
        else:
            lines.append(f"{key}={value}")

    content = "\n".join(lines) + "\n"
    write_file_secure(env_path, content, mode=0o600)

    success(f"Environment file created: {env_path}")
    return env_path


def collect_env_vars_interactive(
    project_name: str,
    stack: str,
    db_info: Optional[dict[str, str]] = None,
    domain: str = "",
    redis_url: str = "",
) -> dict[str, str]:
    """Interactively collect environment variables from the user.

    Auto-populates known values (DB credentials, Redis URL, etc.)
    and prompts for any additional variables.

    Args:
        project_name: Name of the project.
        stack: Stack type (django, fastapi, nextjs, etc.).
        db_info: Database credentials dict (from postgres setup).
        domain: Domain name for the project.
        redis_url: Redis connection URL.

    Returns:
        Dictionary of environment variables.
    """
    env_vars: dict[str, str] = {}

    console.print("\n[bold]Environment Configuration[/bold]")
    console.print("[dim]DeployCraft will auto-fill known values. You can customize any.[/dim]\n")

    # Auto-populate based on what we know
    if stack in ("django", "fastapi"):
        env_vars["SECRET_KEY"] = generate_secret_key()
        env_vars["DEBUG"] = "False"
        env_vars["ALLOWED_HOSTS"] = domain or "*"

        if db_info:
            from deploycraft.services.postgres import get_connection_url

            env_vars["DATABASE_URL"] = get_connection_url(db_info)
            env_vars["DB_NAME"] = db_info["db_name"]
            env_vars["DB_USER"] = db_info["db_user"]
            env_vars["DB_PASSWORD"] = db_info["db_password"]
            env_vars["DB_HOST"] = db_info["db_host"]
            env_vars["DB_PORT"] = db_info["db_port"]

        if redis_url:
            env_vars["REDIS_URL"] = redis_url
            env_vars["CELERY_BROKER_URL"] = redis_url

    elif stack in ("nextjs", "react_vite", "react"):
        env_vars["NODE_ENV"] = "production"
        if db_info:
            from deploycraft.services.postgres import get_connection_url

            env_vars["DATABASE_URL"] = get_connection_url(db_info)
        if redis_url:
            env_vars["REDIS_URL"] = redis_url

    # Show auto-populated values
    if env_vars:
        console.print("[green]Auto-populated variables:[/green]")
        table = Table(show_header=True)
        table.add_column("Variable", style="cyan")
        table.add_column("Value", style="dim")

        for key, value in env_vars.items():
            # Mask passwords in display
            display_value = value
            if "password" in key.lower() or "secret" in key.lower():
                display_value = value[:4] + "****" + value[-4:] if len(value) > 8 else "****"
            table.add_row(key, display_value)

        console.print(table)

    # Ask if user wants to add more
    if Confirm.ask("\nAdd additional environment variables?", default=False):
        console.print("[dim]Enter variables as KEY=VALUE. Empty line to finish.[/dim]")
        while True:
            line = Prompt.ask("  ENV var (KEY=VALUE or empty to finish)", default="")
            if not line:
                break
            if "=" in line:
                key, _, value = line.partition("=")
                env_vars[key.strip()] = value.strip()
            else:
                warning(f"Invalid format: '{line}'. Use KEY=VALUE")

    # Ask if user wants to import from existing .env file
    if Confirm.ask("Import from an existing .env file?", default=False):
        file_path = Prompt.ask("  Path to .env file")
        imported = load_env_from_file(Path(file_path))
        if imported:
            env_vars.update(imported)
            success(f"Imported {len(imported)} variables from {file_path}")

    return env_vars


def load_env_from_file(path: Path) -> dict[str, str]:
    """Parse a .env file into a dictionary.

    Args:
        path: Path to the .env file.

    Returns:
        Dictionary of key-value pairs.
    """
    env_vars = {}
    if not path.exists():
        warning(f"File not found: {path}")
        return env_vars

    for line in path.read_text().splitlines():
        line = line.strip()
        # Skip comments and empty lines
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            env_vars[key] = value

    return env_vars


def symlink_env_to_project(project_name: str, project_path: Path) -> bool:
    """Create a symlink from the release directory to the secure .env file.

    Args:
        project_name: Name of the project.
        project_path: Path to the current release directory.

    Returns:
        True if symlink was created successfully.
    """
    env_source = get_env_file_path(project_name)
    env_target = project_path / ".env"

    if not env_source.exists():
        warning(f"No .env file found for {project_name}")
        return False

    # Remove existing .env in release if any
    if env_target.exists() or env_target.is_symlink():
        env_target.unlink()

    env_target.symlink_to(env_source)
    return True


def update_env_var(project_name: str, key: str, value: str) -> bool:
    """Update a single environment variable in a project's .env file.

    Args:
        project_name: Name of the project.
        key: Environment variable name.
        value: New value.

    Returns:
        True if updated successfully.
    """
    env_path = get_env_file_path(project_name)
    if not env_path.exists():
        warning(f"No .env file for {project_name}")
        return False

    env_vars = load_env_from_file(env_path)
    env_vars[key] = value
    create_env_file(project_name, env_vars)
    return True
